services:
  - type: web
    name: sistema-vendas-backend
    plan: free
    env: java
    rootDir: sistema
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar --server.port=$PORT